# Generated by Django 5.2.5 on 2025-08-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='comments/media/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Documento')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
