# Generated by Django 5.2.5 on 2025-08-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_media_file_comment_media_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='media_file',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='media_type',
        ),
        migrations.AddField(
            model_name='post',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='posts/media/'),
        ),
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Documento')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(),
        ),
    ]
